services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    user: www-data
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_axel_db  # Renommé pour éviter les conflits fréquents
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Pour garder les données en cas d’arrêt

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_axel
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

volumes:
  db_data:
